{% set name = "ggcat" %}
{% set version = "a91ecc9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/algbio/{{ name|lower }}
  git_rev: {{ version }}

build:
  number: 0

  ## need MacOS SDK v > 10.12 to build some dependencies but it's not available
  ## see https://blog.rust-lang.org/2023/09/25/Increasing-Apple-Version-Requirements.html
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('rust') }}
    - git

test:
  commands:
    - ggcat build --help

about:
  home: https://github.com/algbio/ggcat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'GGCAT - Compacted and colored de Bruijn graph construction and querying'

extra:
  identifiers:
    - doi:10.1101/gr.277615.122
  recipe-maintainers:
    - tmaklin

