name: Upload
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    name: Linux Upload
    if: github.repository == 'tmaklin/bioconda-recipes'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 13
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set path
        run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

      - name: Fetch conda install script
        run: |
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{install-and-set-up-conda,configure-conda,common}.sh

      - name: Set up bioconda-utils
        run: bash install-and-set-up-conda.sh

      # This script can be used to reconfigure conda to use the right channel setup.
      - name: Configure conda
        run: bash configure-conda.sh

      - name: Build and upload
        env:
          QUAY_LOGIN: ${{ secrets.QUAY_LOGIN }}
          QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mimic circleci
          OSTYPE: "linux-gnu"
          CI: "true"
        run: |
          set -ex
          eval "$(conda shell.bash hook)"
          conda activate bioconda
          docker pull quay.io/dpryan79/mulled_container:latest
          # bioconda-utils handle-merged-pr recipes config.yml \
          #   --repo bioconda/bioconda-recipes \
          #   --git-range ${BUILD_SOURCEVERSION}~1 ${BUILD_SOURCEVERSION} \
          #   --quay-upload-target biocontainers \
          #   --fallback build
          bioconda-utils build recipes config.yml \
            --docker
          docker rmi quay.io/dpryan79/mulled_container:latest

  build-osx-64:
    name: OSX-64 Upload
    if: github.repository == 'tmaklin/bioconda-recipes'
    runs-on: macos-13
    strategy:
      fail-fast: false
      max-parallel: 4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set path
        run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

      - name: Fetch conda install script
        run: |
          wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{install-and-set-up-conda,configure-conda,common}.sh

      - name: Set up bioconda-utils
        run: bash install-and-set-up-conda.sh

      # This script can be used to reconfigure conda to use the right channel setup.
      - name: Configure conda
        run: bash configure-conda.sh

      - name: Build and Test
        env:
          QUAY_LOGIN: ${{ secrets.QUAY_LOGIN }}
          QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mimic circleci
          OSTYPE: "darwin"
          CI: "true"
        run: |
          set -e
          eval "$(conda shell.bash hook)"
          conda activate bioconda

          # Sets up OSX SDK
          run_conda_forge_build_setup

          # bioconda-utils handle-merged-pr recipes config.yml \
          #   --repo bioconda/bioconda-recipes \
          #   --git-range ${BUILD_SOURCEVERSION}~1 ${BUILD_SOURCEVERSION} \
          #   --fallback build
          bioconda-utils build recipes config.yml

